### ISSUE TITLE
allow react 17

### ISSUE THREAD

**Issue by rafipiccolo** [RaoHai/react-ansi#310]
could u change this in the package.json to allow react v17 ?

i can confirm that it works for me with react 17, if i force install, but it would be better to just install without force.

    "peerDependencies": {
        "react": "^15.0.0 || ^16.0.0",
        "react-dom": "^15.0.0 || ^16.0.0"
    }
it could be

    "react": "^15.0.0 || ^16.0.0 || ^17.0.0",
    "react-dom": "^15.0.0 || ^16.0.0 || ^17.0.0"

**Comment by rafipiccolo** [comment]
pull request done. could merge it plz.

**Comment by RaoHai** [comment]
https://github.com/RaoHai/react-ansi/releases/tag/2.1.4
thanks for your contribution.

**Comment by rafipiccolo** [comment]
Works in 2.1.4
Thanks 👍
